on:
  push:
    branches:
      - main
name: release-please
permissions:
  contents: read

jobs:
  release-please:
    permissions:
      contents: write # for google-github-actions/release-please-action to create release commit
      pull-requests: write # for google-github-actions/release-please-action to create release PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        id: release
        with:
          release-type: node
          package-name: release-please-action
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: '22'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs.releases_created }}
      - name: 'Cache node_modules'
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-node-v22-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v22-
      - name: Install Dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm install
      - name: Run Build
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run release
      - name: Upload Release Asset
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./DemoMonkey-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}-stable.zip
          asset_name: DemoMonkey-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.zip
          asset_content_type: application/zip
