name: Tests for PR

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '22'
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: 'Cache node_modules'
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-node-v22-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v22-
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Run Non-Ui Tests
        run: npm run test-no-ui
